"""squashed: make tool_name optional and allow nv_document in SceneUpdate

Revision ID: 0347281e50a5
Revises: 3da45b181215
Create Date: 2025-08-21 10:00:00.000000

Squashes the following migrations:
- 33dc74a9445f: make tool_name optional in SceneBase
- 0347281e50a5: allow nv_document in SceneUpdate (original)
- 2d3cce9607a4: allow nv_document in SceneUpdate and make tool_name optional in SceneBase

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0347281e50a5'
down_revision = '3da45b181215'  # Changed to skip the squashed migrations
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make tool_name optional in scene table (from 33dc74a9445f)
    op.alter_column('scene', 'tool_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert tool_name to non-nullable
    op.alter_column('scene', 'tool_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
