"""use enum ProcessingStatus and update scene creation logic

Revision ID: 3da45b181215
Revises: 1f21fd187bb2
Create Date: 2025-07-22 13:45:22.438641

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3da45b181215'
down_revision = '1f21fd187bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus').create(op.get_bind())
    op.alter_column('scene', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               existing_nullable=False,
               postgresql_using='status::processingstatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scene', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus').drop(op.get_bind())
    # ### end Alembic commands ###
