"""update user model to link to WorkOS

Revision ID: 9f18a5d1bbc1
Revises: c557e045f969
Create Date: 2025-08-30 10:39:30.665566

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9f18a5d1bbc1'
down_revision = 'c557e045f969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('workos_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    connection = op.get_bind()
    # Generate random WorkOS-style IDs
    connection.execute(sa.text("""
        UPDATE "user" 
        SET workos_id = 'user_' || substr(md5(id::text || email || random()::text), 1, 24)
        WHERE workos_id IS NULL
    """))
    op.create_index(op.f('ix_user_workos_id'), 'user', ['workos_id'], unique=True)
    op.alter_column('user', 'workos_id', nullable=False)
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Populate hashed_password with a default value
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE "user" 
        SET hashed_password = '$2b$12$defaulthashedpassword'
        WHERE hashed_password IS NULL
    """))
    
    # Make hashed_password non-nullable
    op.alter_column('user', 'hashed_password', nullable=False)

    op.drop_index(op.f('ix_user_workos_id'), table_name='user')
    op.drop_column('user', 'workos_id')
    # ### end Alembic commands ###
