"""update user model

Revision ID: c557e045f969
Revises: 87aeedc984f9
Create Date: 2025-08-29 16:08:32.325648

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c557e045f969'
down_revision = '87aeedc984f9'
branch_labels = None
depends_on = None


def upgrade():
    # Add columns as nullable first
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    
    # Simple population with default values
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE "user" 
        SET 
            email = 'user-' || id || '@example.com',
            is_active = true,
            is_superuser = COALESCE(admin, false),
            first_name = COALESCE(name, 'Unknown'),
            last_name = 'User'
        WHERE email IS NULL
    """))
    
    # Create index and make columns non-nullable
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('user', 'email', nullable=False)
    op.alter_column('user', 'is_active', nullable=False)
    op.alter_column('user', 'is_superuser', nullable=False)
    
    # Drop old columns
    op.drop_column('user', 'groups')
    op.drop_column('user', 'last_activity')
    op.drop_column('user', 'scopes')
    op.drop_column('user', 'name')
    op.drop_column('user', 'pending')
    op.drop_column('user', 'admin')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('pending', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('groups', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
